#
# Example configuration for a quadrotor with a Tetracam micro camera.
#

[Planner]
SearchPattern = 1
AutoTakeOff = false
LateralOverlap = 0.8
ForwardOverlap = 0.7
SpatialResolution = 40
TargetVelocity = 17
TargetPlanning = 2

[UAV]
FlightTime = 300
Velocity = 17
MinHeight = 70
MaxHeight = 500
MinVelocity = 5
MaxVelocity = 20

[Camera]
PixelSize = 0.0032
FocalLenght = 8.43
SensorWidth = 6.55
SensorHeight = 4.92
CaptureRate = 3
