#
# This is the configuration file for planning a UAV mission
#

[Planner]
SearchPattern = 3; 1:back and forth, 2:Long Edge, 3:Optimal,
LateralOverlap = 0.6;
FordwardOVerlap = 0.7;
SpatialResolution = 100; mm/pixel
TargetVelocity = 10.0; m/s
TargetPlanning = 2; Planning mode, 1 = resolution, 2 = velocity, 3 = altitude;
AutoTakeOff = true; Autonomous takeoff and landing

[UAV]
FlightTime = 300;Seconds, put 0 to do not consider flight time
MinVelocity = 8.0;
MaxVelocity = 20.0;
MinHeight = 50; meters
MaxHeight = 500; meters

[Camera]
PixelSize = 0.0032; mm
FocalLenght = 8.43; mm
SensorWidth = 6.55; mm
SensorHeight = 4.92; mm


